//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.CorporateCustomerInfoes = new HashSet<CorporateCustomerInfo>();
            this.Customers = new HashSet<Customer>();
            this.Customers1 = new HashSet<Customer>();
            this.Partners = new HashSet<Partner>();
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public long ID { get; set; }
        public long ProvinceID { get; set; }
        public long DistrictID { get; set; }
        public long RuralCode { get; set; }
        public long NeighborhoodID { get; set; }
        public long StreetID { get; set; }
        public long DoorID { get; set; }
        public long ApartmentID { get; set; }
        public long AddressNo { get; set; }
        public string AddressText { get; set; }
        public int PostalCode { get; set; }
        public string ProvinceName { get; set; }
        public string DistrictName { get; set; }
        public string NeighborhoodName { get; set; }
        public string StreetName { get; set; }
        public string DoorNo { get; set; }
        public string ApartmentNo { get; set; }
        public string BuildingName { get; set; }
        public string Floor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorporateCustomerInfo> CorporateCustomerInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partner> Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
