//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedRecurringDiscount
    {
        public long RecurringDiscountID { get; set; }
        public long BillID { get; set; }
        public short ApplicationState { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual RecurringDiscount RecurringDiscount { get; set; }
    }
}
