//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.AppliedRecurringDiscounts = new HashSet<AppliedRecurringDiscount>();
            this.BillFees = new HashSet<BillFee>();
            this.PartnerCredits = new HashSet<PartnerCredit>();
            this.ScheduledSMS = new HashSet<ScheduledSM>();
            this.SMSArchives = new HashSet<SMSArchive>();
            this.SubscriptionCredits = new HashSet<SubscriptionCredit>();
        }
    
        public long ID { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> AccountantID { get; set; }
        public long SubscriptionID { get; set; }
        public short BillStatusID { get; set; }
        public short PaymentTypeID { get; set; }
        public short Source { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedRecurringDiscount> AppliedRecurringDiscounts { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillFee> BillFees { get; set; }
        public virtual EBill EBill { get; set; }
        public virtual ExternalPayment ExternalPayment { get; set; }
        public virtual PartnerBillPayment PartnerBillPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerCredit> PartnerCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduledSM> ScheduledSMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SMSArchive> SMSArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionCredit> SubscriptionCredits { get; set; }
    }
}
