//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTKIPBlock
    {
        public int ID { get; set; }
        public string OperatorName { get; set; }
        public string StartingIP { get; set; }
        public string EndingIP { get; set; }
        public short ServiceType { get; set; }
        public bool UsesNAT { get; set; }
        public System.DateTime AllocationDate { get; set; }
        public Nullable<System.DateTime> DeallocationDate { get; set; }
        public short BlockType { get; set; }
        public string UseLocation { get; set; }
    }
}
