//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTKSchedulerSetting
    {
        public short LogType { get; set; }
        public long SchedulerStartTime { get; set; }
        public long SchedulerActiveTime { get; set; }
        public short SchedulerWorkPeriod { get; set; }
        public string SchedulerStartDay { get; set; }
        public bool PartitionFiles { get; set; }
        public string FTPFolder { get; set; }
        public string FTPUsername { get; set; }
        public string FTPPassword { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LastOperationTime { get; set; }
    }
}
