//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cashier()
        {
            this.CashierBalances = new HashSet<CashierBalance>();
        }
    
        public int ID { get; set; }
        public string CompanyTitle { get; set; }
        public string TaxRegion { get; set; }
        public string TaxNo { get; set; }
        public string Address { get; set; }
        public bool IsEnabled { get; set; }
        public int AppUserID { get; set; }
        public decimal ProfitCut { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashierBalance> CashierBalances { get; set; }
    }
}
