//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSetupTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerSetupTask()
        {
            this.CustomerSetupStatusUpdates = new HashSet<CustomerSetupStatusUpdate>();
            this.SubscriptionSupportRequests = new HashSet<SubscriptionSupportRequest>();
        }
    
        public long ID { get; set; }
        public int SetupUserID { get; set; }
        public long SubscriptionID { get; set; }
        public short TaskType { get; set; }
        public bool HasModem { get; set; }
        public string ModemName { get; set; }
        public short XDSLType { get; set; }
        public System.DateTime TaskIssueDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public short TaskStatus { get; set; }
        public string Details { get; set; }
        public bool IsCharged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSetupStatusUpdate> CustomerSetupStatusUpdates { get; set; }
        public virtual CustomerSetupUser CustomerSetupUser { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionSupportRequest> SubscriptionSupportRequests { get; set; }
    }
}
