//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBill
    {
        public long BillID { get; set; }
        public string BillCode { get; set; }
        public string ReferenceNo { get; set; }
        public System.DateTime Date { get; set; }
        public short EBillType { get; set; }
        public int InternalSerialNo { get; set; }
        public System.DateTime EBillIssueDate { get; set; }
    
        public virtual Bill Bill { get; set; }
    }
}
