//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fee()
        {
            this.BillFees = new HashSet<BillFee>();
        }
    
        public long ID { get; set; }
        public short FeeTypeID { get; set; }
        public short InstallmentBillCount { get; set; }
        public long SubscriptionID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> FeeTypeVariantID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public bool IsCancelled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillFee> BillFees { get; set; }
        public virtual FeeTypeCost FeeTypeCost { get; set; }
        public virtual FeeTypeVariant FeeTypeVariant { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
