//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NA()
        {
            this.NAS1 = new HashSet<NA>();
            this.NASExpiredPools = new HashSet<NASExpiredPool>();
            this.NASNetmaps = new HashSet<NASNetmap>();
            this.NASVerticalIPMaps = new HashSet<NASVerticalIPMap>();
        }
    
        public int ID { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public string Secret { get; set; }
        public int RadiusIncomingPort { get; set; }
        public string ApiUsername { get; set; }
        public string ApiPassword { get; set; }
        public int ApiPort { get; set; }
        public short NATType { get; set; }
        public Nullable<int> BackboneNASID { get; set; }
        public bool Disabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NA> NAS1 { get; set; }
        public virtual NA NA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NASExpiredPool> NASExpiredPools { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NASNetmap> NASNetmaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NASVerticalIPMap> NASVerticalIPMaps { get; set; }
    }
}
