//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflinePaymentGateway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfflinePaymentGateway()
        {
            this.ExternalPayments = new HashSet<ExternalPayment>();
        }
    
        public int ID { get; set; }
        public short Type { get; set; }
        public string Name { get; set; }
        public string FTPAddress { get; set; }
        public string FTPUsername { get; set; }
        public string FTPPassword { get; set; }
        public string ReceiveFolder { get; set; }
        public string SendFolder { get; set; }
        public Nullable<System.DateTime> LastOperationTime { get; set; }
        public string LastProcessedFileName { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExternalPayment> ExternalPayments { get; set; }
    }
}
