//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartnerBillPayments = new HashSet<PartnerBillPayment>();
            this.PartnerCredits = new HashSet<PartnerCredit>();
            this.PartnerPermissions = new HashSet<PartnerPermission>();
            this.PartnerRegisteredSubscriptions = new HashSet<PartnerRegisteredSubscription>();
            this.PartnerSubUsers = new HashSet<PartnerSubUser>();
            this.WorkAreas = new HashSet<WorkArea>();
        }
    
        public int ID { get; set; }
        public int GroupID { get; set; }
        public string Title { get; set; }
        public string ExecutiveFirstName { get; set; }
        public string ExecutiveLastName { get; set; }
        public string ExecutiveTCK { get; set; }
        public string TaxNo { get; set; }
        public string TaxOffice { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public long AddressID { get; set; }
        public int MaxActiveUsers { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CustomerSetupUserID { get; set; }
        public decimal SetupAllowance { get; set; }
        public decimal PaymentAllowance { get; set; }
        public decimal MinAmountForAllowance { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual CustomerSetupUser CustomerSetupUser { get; set; }
        public virtual PartnerGroup PartnerGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerBillPayment> PartnerBillPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerCredit> PartnerCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerPermission> PartnerPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerRegisteredSubscription> PartnerRegisteredSubscriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerSubUser> PartnerSubUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkArea> WorkAreas { get; set; }
    }
}
