//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerRegisteredSubscription
    {
        public long SubscriptionID { get; set; }
        public int PartnerID { get; set; }
        public int TariffID { get; set; }
        public Nullable<short> Commitment { get; set; }
        public decimal Allowance { get; set; }
        public decimal AllowanceThreshold { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> PaymentUserID { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual Service Service { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
