//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiusAccountingIPInfo
    {
        public long RadiusAccountingID { get; set; }
        public string LocalIP { get; set; }
        public string RealIP { get; set; }
        public string PortRange { get; set; }
    
        public virtual RadiusAccounting RadiusAccounting { get; set; }
    }
}
