//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiusAccounting
    {
        public long ID { get; set; }
        public string SessionID { get; set; }
        public string UniqueID { get; set; }
        public string Username { get; set; }
        public string NASIP { get; set; }
        public string NASPort { get; set; }
        public string NASportType { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> StopTime { get; set; }
        public long SessionTime { get; set; }
        public long UploadBytes { get; set; }
        public long DownloadBytes { get; set; }
        public string CalledStationID { get; set; }
        public string CallingStationID { get; set; }
        public Nullable<short> TerminateCause { get; set; }
        public short ServiceType { get; set; }
        public short FramedProtocol { get; set; }
        public string FramedIPAddress { get; set; }
        public long SubscriptionID { get; set; }
    
        public virtual Subscription Subscription { get; set; }
        public virtual RadiusAccountingIPInfo RadiusAccountingIPInfo { get; set; }
    }
}
