//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RadiusR_NetSpeed_5Entities : DbContext
    {
        public RadiusR_NetSpeed_5Entities()
            : base("name=RadiusR_NetSpeed_5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VerimorOperationResponse> VerimorOperationResponses { get; set; }
        public virtual DbSet<VerimorOperation> VerimorOperations { get; set; }
        public virtual DbSet<GeneralFault> GeneralFaults { get; set; }
    }
}
