//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringDiscount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecurringDiscount()
        {
            this.AppliedRecurringDiscounts = new HashSet<AppliedRecurringDiscount>();
            this.RecurringDiscount1 = new HashSet<RecurringDiscount>();
        }
    
        public long ID { get; set; }
        public long SubscriptionID { get; set; }
        public System.DateTime CreationTime { get; set; }
        public short DiscountType { get; set; }
        public short ApplicationType { get; set; }
        public decimal Amount { get; set; }
        public int ApplicationTimes { get; set; }
        public Nullable<short> FeeTypeID { get; set; }
        public bool IsDisabled { get; set; }
        public bool OnlyFullInvoice { get; set; }
        public string Description { get; set; }
        public Nullable<long> ReferrerRecurringDiscountID { get; set; }
        public Nullable<System.DateTime> CancellationDate { get; set; }
        public Nullable<short> CancellationCause { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedRecurringDiscount> AppliedRecurringDiscounts { get; set; }
        public virtual FeeTypeCost FeeTypeCost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringDiscount> RecurringDiscount1 { get; set; }
        public virtual RecurringDiscount RecurringDiscount2 { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
