//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduledSM
    {
        public long ID { get; set; }
        public short SMSType { get; set; }
        public long SubscriptionID { get; set; }
        public Nullable<long> BillID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public string CalculatedParameters { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
