//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialOffer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public short DiscountType { get; set; }
        public short ApplicationType { get; set; }
        public decimal Amount { get; set; }
        public int ApplicationTimes { get; set; }
        public Nullable<short> FeeTypeID { get; set; }
        public bool OnlyFullInvoice { get; set; }
        public bool IsReferral { get; set; }
    
        public virtual FeeTypeCost FeeTypeCost { get; set; }
    }
}
