//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionSupportRequest
    {
        public long ID { get; set; }
        public long SubscriptionID { get; set; }
        public string Message { get; set; }
        public string SupportResponse { get; set; }
        public short StateID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<long> CustomerSetupTaskID { get; set; }
        public Nullable<int> IssuerID { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual CustomerSetupTask CustomerSetupTask { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
