//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public long ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> AppUserID { get; set; }
        public int LogType { get; set; }
        public Nullable<long> SubscriptionID { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Parameters { get; set; }
        public short Interface { get; set; }
        public string InterfaceUsername { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Subscription Subscription { get; set; }
    }
}
