//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelekomWorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TelekomWorkOrder()
        {
            this.TelekomWorkOrderParameters = new HashSet<TelekomWorkOrderParameter>();
        }
    
        public long ID { get; set; }
        public short OperationTypeID { get; set; }
        public short OperationSubType { get; set; }
        public int ManagementCode { get; set; }
        public int ProvinceCode { get; set; }
        public long QueueNo { get; set; }
        public long SubscriptionID { get; set; }
        public bool IsOpen { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> LastRetryDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public Nullable<int> AppUserID { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TelekomWorkOrderParameter> TelekomWorkOrderParameters { get; set; }
    }
}
