//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TelekomWorkOrderParameter
    {
        public long ID { get; set; }
        public long WorkOrderID { get; set; }
        public int ParameterCode { get; set; }
        public string Value { get; set; }
    
        public virtual TelekomWorkOrder TelekomWorkOrder { get; set; }
    }
}
