//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerimorSMSReport
    {
        public long message_id { get; set; }
        public Nullable<int> campaign_id { get; set; }
        public string campaign_custom_id { get; set; }
        public string message_custom_id { get; set; }
        public string dest { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> international_multiplier { get; set; }
        public Nullable<int> credits { get; set; }
        public string status { get; set; }
        public string gsm_error { get; set; }
        public string sent_at { get; set; }
        public string done_at { get; set; }
        public string direction { get; set; }
    }
}
