//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerimorCallRecord
    {
        public int RecordsID { get; set; }
        public string call_uuid { get; set; }
        public string phoneNo { get; set; }
        public string start_stamp { get; set; }
        public string direction { get; set; }
        public string caller_id_number { get; set; }
        public string destination_number { get; set; }
        public string duration { get; set; }
        public string hangup_cause { get; set; }
    }
}
