//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerimorOperationResult
    {
        public int ID { get; set; }
        public int OperationTypeID { get; set; }
        public int OperationResult { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
