//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Verimor.Webhook.EventListener.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerimorOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VerimorOperation()
        {
            this.VerimorOperationResponses = new HashSet<VerimorOperationResponse>();
        }
    
        public int ID { get; set; }
        public Nullable<int> operationType { get; set; }
        public string phrase { get; set; }
        public string announcementID { get; set; }
        public string target { get; set; }
        public string min_digits { get; set; }
        public string max_digits { get; set; }
        public string retry_count { get; set; }
        public string param_name { get; set; }
        public string service_url { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerimorOperationResponse> VerimorOperationResponses { get; set; }
    }
}
