//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.VPOS.Custom.VakifbankVPOSReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="PayFlexVPosWebService", ConfigurationName="VakifbankVPOSReference.TransactionWebServicesSoap")]
    public interface TransactionWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="PayFlexVPosWebService/ExecuteVposRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RadiusR.VPOS.Custom.VakifbankVPOSReference.VposResponse ExecuteVposRequest(RadiusR.VPOS.Custom.VakifbankVPOSReference.VposRequest vposRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="PayFlexVPosWebService/ExecuteVposRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<RadiusR.VPOS.Custom.VakifbankVPOSReference.VposResponse> ExecuteVposRequestAsync(RadiusR.VPOS.Custom.VakifbankVPOSReference.VposRequest vposRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class VposRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantIdField;
        
        private string identityField;
        
        private string passwordField;
        
        private string terminalNoField;
        
        private string transactionTypeField;
        
        private string apiTransactionTypeField;
        
        private string transactionIdField;
        
        private string referenceTransactionIdField;
        
        private System.Nullable<int> numberOfInstallmentsField;
        
        private bool numberOfInstallmentsFieldSpecified;
        
        private System.Nullable<decimal> currencyAmountField;
        
        private bool currencyAmountFieldSpecified;
        
        private System.Nullable<decimal> surchargeAmountField;
        
        private bool surchargeAmountFieldSpecified;
        
        private System.Nullable<int> currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private System.Nullable<decimal> pointAmountField;
        
        private bool pointAmountFieldSpecified;
        
        private System.Nullable<int> pointCodeField;
        
        private bool pointCodeFieldSpecified;
        
        private string panField;
        
        private string cardNoFirstField;
        
        private string cardNoLastField;
        
        private string installmentCountField;
        
        private string inquiryValueField;
        
        private string cvvField;
        
        private string securityCodeField;
        
        private string expiryField;
        
        private System.Nullable<int> locationField;
        
        private bool locationFieldSpecified;
        
        private string extractField;
        
        private System.Nullable<int> deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private string cardHoldersNameField;
        
        private string clientIpField;
        
        private string merchantIpField;
        
        private string cardHoldersEmailField;
        
        private string orderIdField;
        
        private string orderDescriptionField;
        
        private string triggerDateField;
        
        private System.Nullable<bool> isRecurringField;
        
        private bool isRecurringFieldSpecified;
        
        private string recurringFrequencyTypeField;
        
        private System.Nullable<int> recurringFrequencyField;
        
        private bool recurringFrequencyFieldSpecified;
        
        private System.Nullable<int> recurringInstallmentCountField;
        
        private bool recurringInstallmentCountFieldSpecified;
        
        private string mpiTransactionIdField;
        
        private string expSignField;
        
        private string cAVVField;
        
        private string eCIField;
        
        private Item[] customItemsField;
        
        private CustomInstallments customInstallmentsField;
        
        private string brandNameField;
        
        private string panMaskedField;
        
        private string cvvMaskedField;
        
        private System.Nullable<int> transactionDeviceSourceField;
        
        private bool transactionDeviceSourceFieldSpecified;
        
        private string securityCodeMaskedField;
        
        private string customerNumberField;
        
        private string customerNameField;
        
        private string panCodeField;
        
        private string hostSubMerchantIdField;
        
        private System.Nullable<int> merchantTypeField;
        
        private bool merchantTypeFieldSpecified;
        
        private System.Nullable<int> transactionSourceField;
        
        private bool transactionSourceFieldSpecified;
        
        private System.Nullable<bool> includeHostResultCodeField;
        
        private bool includeHostResultCodeFieldSpecified;
        
        private CampaignInfo[] campaignResultField;
        
        private string storeNoField;
        
        private System.Nullable<int> transactionChannelField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
                this.RaisePropertyChanged("Identity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TerminalNo {
            get {
                return this.terminalNoField;
            }
            set {
                this.terminalNoField = value;
                this.RaisePropertyChanged("TerminalNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ApiTransactionType {
            get {
                return this.apiTransactionTypeField;
            }
            set {
                this.apiTransactionTypeField = value;
                this.RaisePropertyChanged("ApiTransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ReferenceTransactionId {
            get {
                return this.referenceTransactionIdField;
            }
            set {
                this.referenceTransactionIdField = value;
                this.RaisePropertyChanged("ReferenceTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> NumberOfInstallments {
            get {
                return this.numberOfInstallmentsField;
            }
            set {
                this.numberOfInstallmentsField = value;
                this.RaisePropertyChanged("NumberOfInstallments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfInstallmentsSpecified {
            get {
                return this.numberOfInstallmentsFieldSpecified;
            }
            set {
                this.numberOfInstallmentsFieldSpecified = value;
                this.RaisePropertyChanged("NumberOfInstallmentsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> CurrencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
                this.RaisePropertyChanged("CurrencyAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyAmountSpecified {
            get {
                return this.currencyAmountFieldSpecified;
            }
            set {
                this.currencyAmountFieldSpecified = value;
                this.RaisePropertyChanged("CurrencyAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> SurchargeAmount {
            get {
                return this.surchargeAmountField;
            }
            set {
                this.surchargeAmountField = value;
                this.RaisePropertyChanged("SurchargeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeAmountSpecified {
            get {
                return this.surchargeAmountFieldSpecified;
            }
            set {
                this.surchargeAmountFieldSpecified = value;
                this.RaisePropertyChanged("SurchargeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("CurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyCodeSpecified {
            get {
                return this.currencyCodeFieldSpecified;
            }
            set {
                this.currencyCodeFieldSpecified = value;
                this.RaisePropertyChanged("CurrencyCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> PointAmount {
            get {
                return this.pointAmountField;
            }
            set {
                this.pointAmountField = value;
                this.RaisePropertyChanged("PointAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointAmountSpecified {
            get {
                return this.pointAmountFieldSpecified;
            }
            set {
                this.pointAmountFieldSpecified = value;
                this.RaisePropertyChanged("PointAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<int> PointCode {
            get {
                return this.pointCodeField;
            }
            set {
                this.pointCodeField = value;
                this.RaisePropertyChanged("PointCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointCodeSpecified {
            get {
                return this.pointCodeFieldSpecified;
            }
            set {
                this.pointCodeFieldSpecified = value;
                this.RaisePropertyChanged("PointCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
                this.RaisePropertyChanged("Pan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CardNoFirst {
            get {
                return this.cardNoFirstField;
            }
            set {
                this.cardNoFirstField = value;
                this.RaisePropertyChanged("CardNoFirst");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CardNoLast {
            get {
                return this.cardNoLastField;
            }
            set {
                this.cardNoLastField = value;
                this.RaisePropertyChanged("CardNoLast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string InstallmentCount {
            get {
                return this.installmentCountField;
            }
            set {
                this.installmentCountField = value;
                this.RaisePropertyChanged("InstallmentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string InquiryValue {
            get {
                return this.inquiryValueField;
            }
            set {
                this.inquiryValueField = value;
                this.RaisePropertyChanged("InquiryValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Cvv {
            get {
                return this.cvvField;
            }
            set {
                this.cvvField = value;
                this.RaisePropertyChanged("Cvv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SecurityCode {
            get {
                return this.securityCodeField;
            }
            set {
                this.securityCodeField = value;
                this.RaisePropertyChanged("SecurityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Expiry {
            get {
                return this.expiryField;
            }
            set {
                this.expiryField = value;
                this.RaisePropertyChanged("Expiry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<int> Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified {
            get {
                return this.locationFieldSpecified;
            }
            set {
                this.locationFieldSpecified = value;
                this.RaisePropertyChanged("LocationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Extract {
            get {
                return this.extractField;
            }
            set {
                this.extractField = value;
                this.RaisePropertyChanged("Extract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("DeviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("DeviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CardHoldersName {
            get {
                return this.cardHoldersNameField;
            }
            set {
                this.cardHoldersNameField = value;
                this.RaisePropertyChanged("CardHoldersName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string ClientIp {
            get {
                return this.clientIpField;
            }
            set {
                this.clientIpField = value;
                this.RaisePropertyChanged("ClientIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string MerchantIp {
            get {
                return this.merchantIpField;
            }
            set {
                this.merchantIpField = value;
                this.RaisePropertyChanged("MerchantIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string CardHoldersEmail {
            get {
                return this.cardHoldersEmailField;
            }
            set {
                this.cardHoldersEmailField = value;
                this.RaisePropertyChanged("CardHoldersEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string OrderDescription {
            get {
                return this.orderDescriptionField;
            }
            set {
                this.orderDescriptionField = value;
                this.RaisePropertyChanged("OrderDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string TriggerDate {
            get {
                return this.triggerDateField;
            }
            set {
                this.triggerDateField = value;
                this.RaisePropertyChanged("TriggerDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<bool> IsRecurring {
            get {
                return this.isRecurringField;
            }
            set {
                this.isRecurringField = value;
                this.RaisePropertyChanged("IsRecurring");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsRecurringSpecified {
            get {
                return this.isRecurringFieldSpecified;
            }
            set {
                this.isRecurringFieldSpecified = value;
                this.RaisePropertyChanged("IsRecurringSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string RecurringFrequencyType {
            get {
                return this.recurringFrequencyTypeField;
            }
            set {
                this.recurringFrequencyTypeField = value;
                this.RaisePropertyChanged("RecurringFrequencyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<int> RecurringFrequency {
            get {
                return this.recurringFrequencyField;
            }
            set {
                this.recurringFrequencyField = value;
                this.RaisePropertyChanged("RecurringFrequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringFrequencySpecified {
            get {
                return this.recurringFrequencyFieldSpecified;
            }
            set {
                this.recurringFrequencyFieldSpecified = value;
                this.RaisePropertyChanged("RecurringFrequencySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public System.Nullable<int> RecurringInstallmentCount {
            get {
                return this.recurringInstallmentCountField;
            }
            set {
                this.recurringInstallmentCountField = value;
                this.RaisePropertyChanged("RecurringInstallmentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringInstallmentCountSpecified {
            get {
                return this.recurringInstallmentCountFieldSpecified;
            }
            set {
                this.recurringInstallmentCountFieldSpecified = value;
                this.RaisePropertyChanged("RecurringInstallmentCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string MpiTransactionId {
            get {
                return this.mpiTransactionIdField;
            }
            set {
                this.mpiTransactionIdField = value;
                this.RaisePropertyChanged("MpiTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string ExpSign {
            get {
                return this.expSignField;
            }
            set {
                this.expSignField = value;
                this.RaisePropertyChanged("ExpSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string CAVV {
            get {
                return this.cAVVField;
            }
            set {
                this.cAVVField = value;
                this.RaisePropertyChanged("CAVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string ECI {
            get {
                return this.eCIField;
            }
            set {
                this.eCIField = value;
                this.RaisePropertyChanged("ECI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=40)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item[] CustomItems {
            get {
                return this.customItemsField;
            }
            set {
                this.customItemsField = value;
                this.RaisePropertyChanged("CustomItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public CustomInstallments CustomInstallments {
            get {
                return this.customInstallmentsField;
            }
            set {
                this.customInstallmentsField = value;
                this.RaisePropertyChanged("CustomInstallments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string BrandName {
            get {
                return this.brandNameField;
            }
            set {
                this.brandNameField = value;
                this.RaisePropertyChanged("BrandName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string PanMasked {
            get {
                return this.panMaskedField;
            }
            set {
                this.panMaskedField = value;
                this.RaisePropertyChanged("PanMasked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string CvvMasked {
            get {
                return this.cvvMaskedField;
            }
            set {
                this.cvvMaskedField = value;
                this.RaisePropertyChanged("CvvMasked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public System.Nullable<int> TransactionDeviceSource {
            get {
                return this.transactionDeviceSourceField;
            }
            set {
                this.transactionDeviceSourceField = value;
                this.RaisePropertyChanged("TransactionDeviceSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDeviceSourceSpecified {
            get {
                return this.transactionDeviceSourceFieldSpecified;
            }
            set {
                this.transactionDeviceSourceFieldSpecified = value;
                this.RaisePropertyChanged("TransactionDeviceSourceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string SecurityCodeMasked {
            get {
                return this.securityCodeMaskedField;
            }
            set {
                this.securityCodeMaskedField = value;
                this.RaisePropertyChanged("SecurityCodeMasked");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
                this.RaisePropertyChanged("CustomerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
                this.RaisePropertyChanged("CustomerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string PanCode {
            get {
                return this.panCodeField;
            }
            set {
                this.panCodeField = value;
                this.RaisePropertyChanged("PanCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string HostSubMerchantId {
            get {
                return this.hostSubMerchantIdField;
            }
            set {
                this.hostSubMerchantIdField = value;
                this.RaisePropertyChanged("HostSubMerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public System.Nullable<int> MerchantType {
            get {
                return this.merchantTypeField;
            }
            set {
                this.merchantTypeField = value;
                this.RaisePropertyChanged("MerchantType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantTypeSpecified {
            get {
                return this.merchantTypeFieldSpecified;
            }
            set {
                this.merchantTypeFieldSpecified = value;
                this.RaisePropertyChanged("MerchantTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public System.Nullable<int> TransactionSource {
            get {
                return this.transactionSourceField;
            }
            set {
                this.transactionSourceField = value;
                this.RaisePropertyChanged("TransactionSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionSourceSpecified {
            get {
                return this.transactionSourceFieldSpecified;
            }
            set {
                this.transactionSourceFieldSpecified = value;
                this.RaisePropertyChanged("TransactionSourceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=53)]
        public System.Nullable<bool> IncludeHostResultCode {
            get {
                return this.includeHostResultCodeField;
            }
            set {
                this.includeHostResultCodeField = value;
                this.RaisePropertyChanged("IncludeHostResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncludeHostResultCodeSpecified {
            get {
                return this.includeHostResultCodeFieldSpecified;
            }
            set {
                this.includeHostResultCodeFieldSpecified = value;
                this.RaisePropertyChanged("IncludeHostResultCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=54)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignItem", IsNullable=false)]
        public CampaignInfo[] CampaignResult {
            get {
                return this.campaignResultField;
            }
            set {
                this.campaignResultField = value;
                this.RaisePropertyChanged("CampaignResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string StoreNo {
            get {
                return this.storeNoField;
            }
            set {
                this.storeNoField = value;
                this.RaisePropertyChanged("StoreNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=56)]
        public System.Nullable<int> TransactionChannel {
            get {
                return this.transactionChannelField;
            }
            set {
                this.transactionChannelField = value;
                this.RaisePropertyChanged("TransactionChannel");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        private string customTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customType {
            get {
                return this.customTypeField;
            }
            set {
                this.customTypeField = value;
                this.RaisePropertyChanged("customType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class PlanSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int maturityPeriodField;
        
        private int frequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maturityPeriod {
            get {
                return this.maturityPeriodField;
            }
            set {
                this.maturityPeriodField = value;
                this.RaisePropertyChanged("maturityPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("frequency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class LimitSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private decimal limitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal limit {
            get {
                return this.limitField;
            }
            set {
                this.limitField = value;
                this.RaisePropertyChanged("limit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class MerchantCampaignResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hostResponseCodeField;
        
        private string hostResponseMessageField;
        
        private CampaignInfo[] campaignInfosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HostResponseCode {
            get {
                return this.hostResponseCodeField;
            }
            set {
                this.hostResponseCodeField = value;
                this.RaisePropertyChanged("HostResponseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HostResponseMessage {
            get {
                return this.hostResponseMessageField;
            }
            set {
                this.hostResponseMessageField = value;
                this.RaisePropertyChanged("HostResponseMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public CampaignInfo[] CampaignInfos {
            get {
                return this.campaignInfosField;
            }
            set {
                this.campaignInfosField = value;
                this.RaisePropertyChanged("CampaignInfos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class CampaignInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string actionField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class InstallmentItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class VposResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string merchantIdField;
        
        private string transactionTypeField;
        
        private string transactionIdField;
        
        private string referenceTransactionIdField;
        
        private string resultCodeField;
        
        private string resultDetailField;
        
        private Item[] customItemsField;
        
        private InstallmentItem[] installmentTableField;
        
        private CampaignInfo[] campaignResultField;
        
        private MerchantCampaignResult merchantCampaignResultField;
        
        private string authCodeField;
        
        private string hostDateField;
        
        private string rrnField;
        
        private System.Nullable<decimal> pointLostsField;
        
        private bool pointLostsFieldSpecified;
        
        private string terminalNoField;
        
        private System.Nullable<decimal> pointAmountField;
        
        private bool pointAmountFieldSpecified;
        
        private System.Nullable<int> pointCodeField;
        
        private bool pointCodeFieldSpecified;
        
        private System.Nullable<decimal> gainedPointField;
        
        private bool gainedPointFieldSpecified;
        
        private System.Nullable<decimal> totalPointField;
        
        private bool totalPointFieldSpecified;
        
        private System.Nullable<decimal> currencyAmountField;
        
        private bool currencyAmountFieldSpecified;
        
        private System.Nullable<int> currencyCodeField;
        
        private bool currencyCodeFieldSpecified;
        
        private System.Nullable<decimal> vftAmountField;
        
        private bool vftAmountFieldSpecified;
        
        private System.Nullable<decimal> surchargeAmountField;
        
        private bool surchargeAmountFieldSpecified;
        
        private System.Nullable<int> numberOfInstallmentsField;
        
        private bool numberOfInstallmentsFieldSpecified;
        
        private System.Nullable<int> installmentCountField;
        
        private bool installmentCountFieldSpecified;
        
        private System.Nullable<int> recurringInstallmentCountField;
        
        private bool recurringInstallmentCountFieldSpecified;
        
        private string orderIdField;
        
        private string eCIField;
        
        private System.Nullable<int> threeDSecureTypeField;
        
        private bool threeDSecureTypeFieldSpecified;
        
        private System.Nullable<int> transactionDeviceSourceField;
        
        private bool transactionDeviceSourceFieldSpecified;
        
        private System.Nullable<int> locationField;
        
        private bool locationFieldSpecified;
        
        private System.Nullable<int> deviceTypeField;
        
        private bool deviceTypeFieldSpecified;
        
        private System.Nullable<int> batchNoField;
        
        private bool batchNoFieldSpecified;
        
        private string panCodeField;
        
        private System.Nullable<decimal> tLAmountField;
        
        private bool tLAmountFieldSpecified;
        
        private LimitSearchResult[] limitSearchResultsField;
        
        private PlanSearchResult[] planSearchResultsField;
        
        private string hostSubMerchantIdField;
        
        private string identityField;
        
        private System.Nullable<int> merchantTypeField;
        
        private bool merchantTypeFieldSpecified;
        
        private string hostResultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MerchantId {
            get {
                return this.merchantIdField;
            }
            set {
                this.merchantIdField = value;
                this.RaisePropertyChanged("MerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
                this.RaisePropertyChanged("TransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenceTransactionId {
            get {
                return this.referenceTransactionIdField;
            }
            set {
                this.referenceTransactionIdField = value;
                this.RaisePropertyChanged("ReferenceTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResultDetail {
            get {
                return this.resultDetailField;
            }
            set {
                this.resultDetailField = value;
                this.RaisePropertyChanged("ResultDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Item[] CustomItems {
            get {
                return this.customItemsField;
            }
            set {
                this.customItemsField = value;
                this.RaisePropertyChanged("CustomItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public InstallmentItem[] InstallmentTable {
            get {
                return this.installmentTableField;
            }
            set {
                this.installmentTableField = value;
                this.RaisePropertyChanged("InstallmentTable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CampaignItem", IsNullable=false)]
        public CampaignInfo[] CampaignResult {
            get {
                return this.campaignResultField;
            }
            set {
                this.campaignResultField = value;
                this.RaisePropertyChanged("CampaignResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public MerchantCampaignResult MerchantCampaignResult {
            get {
                return this.merchantCampaignResultField;
            }
            set {
                this.merchantCampaignResultField = value;
                this.RaisePropertyChanged("MerchantCampaignResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string HostDate {
            get {
                return this.hostDateField;
            }
            set {
                this.hostDateField = value;
                this.RaisePropertyChanged("HostDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Rrn {
            get {
                return this.rrnField;
            }
            set {
                this.rrnField = value;
                this.RaisePropertyChanged("Rrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> PointLosts {
            get {
                return this.pointLostsField;
            }
            set {
                this.pointLostsField = value;
                this.RaisePropertyChanged("PointLosts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointLostsSpecified {
            get {
                return this.pointLostsFieldSpecified;
            }
            set {
                this.pointLostsFieldSpecified = value;
                this.RaisePropertyChanged("PointLostsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TerminalNo {
            get {
                return this.terminalNoField;
            }
            set {
                this.terminalNoField = value;
                this.RaisePropertyChanged("TerminalNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> PointAmount {
            get {
                return this.pointAmountField;
            }
            set {
                this.pointAmountField = value;
                this.RaisePropertyChanged("PointAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointAmountSpecified {
            get {
                return this.pointAmountFieldSpecified;
            }
            set {
                this.pointAmountFieldSpecified = value;
                this.RaisePropertyChanged("PointAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<int> PointCode {
            get {
                return this.pointCodeField;
            }
            set {
                this.pointCodeField = value;
                this.RaisePropertyChanged("PointCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PointCodeSpecified {
            get {
                return this.pointCodeFieldSpecified;
            }
            set {
                this.pointCodeFieldSpecified = value;
                this.RaisePropertyChanged("PointCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> GainedPoint {
            get {
                return this.gainedPointField;
            }
            set {
                this.gainedPointField = value;
                this.RaisePropertyChanged("GainedPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GainedPointSpecified {
            get {
                return this.gainedPointFieldSpecified;
            }
            set {
                this.gainedPointFieldSpecified = value;
                this.RaisePropertyChanged("GainedPointSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> TotalPoint {
            get {
                return this.totalPointField;
            }
            set {
                this.totalPointField = value;
                this.RaisePropertyChanged("TotalPoint");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPointSpecified {
            get {
                return this.totalPointFieldSpecified;
            }
            set {
                this.totalPointFieldSpecified = value;
                this.RaisePropertyChanged("TotalPointSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> CurrencyAmount {
            get {
                return this.currencyAmountField;
            }
            set {
                this.currencyAmountField = value;
                this.RaisePropertyChanged("CurrencyAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyAmountSpecified {
            get {
                return this.currencyAmountFieldSpecified;
            }
            set {
                this.currencyAmountFieldSpecified = value;
                this.RaisePropertyChanged("CurrencyAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<int> CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("CurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CurrencyCodeSpecified {
            get {
                return this.currencyCodeFieldSpecified;
            }
            set {
                this.currencyCodeFieldSpecified = value;
                this.RaisePropertyChanged("CurrencyCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public System.Nullable<decimal> VftAmount {
            get {
                return this.vftAmountField;
            }
            set {
                this.vftAmountField = value;
                this.RaisePropertyChanged("VftAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VftAmountSpecified {
            get {
                return this.vftAmountFieldSpecified;
            }
            set {
                this.vftAmountFieldSpecified = value;
                this.RaisePropertyChanged("VftAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public System.Nullable<decimal> SurchargeAmount {
            get {
                return this.surchargeAmountField;
            }
            set {
                this.surchargeAmountField = value;
                this.RaisePropertyChanged("SurchargeAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SurchargeAmountSpecified {
            get {
                return this.surchargeAmountFieldSpecified;
            }
            set {
                this.surchargeAmountFieldSpecified = value;
                this.RaisePropertyChanged("SurchargeAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<int> NumberOfInstallments {
            get {
                return this.numberOfInstallmentsField;
            }
            set {
                this.numberOfInstallmentsField = value;
                this.RaisePropertyChanged("NumberOfInstallments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberOfInstallmentsSpecified {
            get {
                return this.numberOfInstallmentsFieldSpecified;
            }
            set {
                this.numberOfInstallmentsFieldSpecified = value;
                this.RaisePropertyChanged("NumberOfInstallmentsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<int> InstallmentCount {
            get {
                return this.installmentCountField;
            }
            set {
                this.installmentCountField = value;
                this.RaisePropertyChanged("InstallmentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstallmentCountSpecified {
            get {
                return this.installmentCountFieldSpecified;
            }
            set {
                this.installmentCountFieldSpecified = value;
                this.RaisePropertyChanged("InstallmentCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<int> RecurringInstallmentCount {
            get {
                return this.recurringInstallmentCountField;
            }
            set {
                this.recurringInstallmentCountField = value;
                this.RaisePropertyChanged("RecurringInstallmentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecurringInstallmentCountSpecified {
            get {
                return this.recurringInstallmentCountFieldSpecified;
            }
            set {
                this.recurringInstallmentCountFieldSpecified = value;
                this.RaisePropertyChanged("RecurringInstallmentCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string OrderId {
            get {
                return this.orderIdField;
            }
            set {
                this.orderIdField = value;
                this.RaisePropertyChanged("OrderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string ECI {
            get {
                return this.eCIField;
            }
            set {
                this.eCIField = value;
                this.RaisePropertyChanged("ECI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<int> ThreeDSecureType {
            get {
                return this.threeDSecureTypeField;
            }
            set {
                this.threeDSecureTypeField = value;
                this.RaisePropertyChanged("ThreeDSecureType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ThreeDSecureTypeSpecified {
            get {
                return this.threeDSecureTypeFieldSpecified;
            }
            set {
                this.threeDSecureTypeFieldSpecified = value;
                this.RaisePropertyChanged("ThreeDSecureTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<int> TransactionDeviceSource {
            get {
                return this.transactionDeviceSourceField;
            }
            set {
                this.transactionDeviceSourceField = value;
                this.RaisePropertyChanged("TransactionDeviceSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionDeviceSourceSpecified {
            get {
                return this.transactionDeviceSourceFieldSpecified;
            }
            set {
                this.transactionDeviceSourceFieldSpecified = value;
                this.RaisePropertyChanged("TransactionDeviceSourceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<int> Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LocationSpecified {
            get {
                return this.locationFieldSpecified;
            }
            set {
                this.locationFieldSpecified = value;
                this.RaisePropertyChanged("LocationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<int> DeviceType {
            get {
                return this.deviceTypeField;
            }
            set {
                this.deviceTypeField = value;
                this.RaisePropertyChanged("DeviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeviceTypeSpecified {
            get {
                return this.deviceTypeFieldSpecified;
            }
            set {
                this.deviceTypeFieldSpecified = value;
                this.RaisePropertyChanged("DeviceTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<int> BatchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
                this.RaisePropertyChanged("BatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatchNoSpecified {
            get {
                return this.batchNoFieldSpecified;
            }
            set {
                this.batchNoFieldSpecified = value;
                this.RaisePropertyChanged("BatchNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string PanCode {
            get {
                return this.panCodeField;
            }
            set {
                this.panCodeField = value;
                this.RaisePropertyChanged("PanCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<decimal> TLAmount {
            get {
                return this.tLAmountField;
            }
            set {
                this.tLAmountField = value;
                this.RaisePropertyChanged("TLAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TLAmountSpecified {
            get {
                return this.tLAmountFieldSpecified;
            }
            set {
                this.tLAmountFieldSpecified = value;
                this.RaisePropertyChanged("TLAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=35)]
        public LimitSearchResult[] LimitSearchResults {
            get {
                return this.limitSearchResultsField;
            }
            set {
                this.limitSearchResultsField = value;
                this.RaisePropertyChanged("LimitSearchResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=36)]
        public PlanSearchResult[] PlanSearchResults {
            get {
                return this.planSearchResultsField;
            }
            set {
                this.planSearchResultsField = value;
                this.RaisePropertyChanged("PlanSearchResults");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string HostSubMerchantId {
            get {
                return this.hostSubMerchantIdField;
            }
            set {
                this.hostSubMerchantIdField = value;
                this.RaisePropertyChanged("HostSubMerchantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
                this.RaisePropertyChanged("Identity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<int> MerchantType {
            get {
                return this.merchantTypeField;
            }
            set {
                this.merchantTypeField = value;
                this.RaisePropertyChanged("MerchantType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantTypeSpecified {
            get {
                return this.merchantTypeFieldSpecified;
            }
            set {
                this.merchantTypeFieldSpecified = value;
                this.RaisePropertyChanged("MerchantTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string HostResultCode {
            get {
                return this.hostResultCodeField;
            }
            set {
                this.hostResultCodeField = value;
                this.RaisePropertyChanged("HostResultCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class CustomInstallment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="PayFlexVPosWebService")]
    public partial class CustomInstallments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CustomInstallment[] customInstallmentField;
        
        private System.Nullable<int> maturityPeriodField;
        
        private System.Nullable<int> frequencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomInstallment", Order=0)]
        public CustomInstallment[] CustomInstallment {
            get {
                return this.customInstallmentField;
            }
            set {
                this.customInstallmentField = value;
                this.RaisePropertyChanged("CustomInstallment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> MaturityPeriod {
            get {
                return this.maturityPeriodField;
            }
            set {
                this.maturityPeriodField = value;
                this.RaisePropertyChanged("MaturityPeriod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> Frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("Frequency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionWebServicesSoapChannel : RadiusR.VPOS.Custom.VakifbankVPOSReference.TransactionWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionWebServicesSoapClient : System.ServiceModel.ClientBase<RadiusR.VPOS.Custom.VakifbankVPOSReference.TransactionWebServicesSoap>, RadiusR.VPOS.Custom.VakifbankVPOSReference.TransactionWebServicesSoap {
        
        public TransactionWebServicesSoapClient() {
        }
        
        public TransactionWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RadiusR.VPOS.Custom.VakifbankVPOSReference.VposResponse ExecuteVposRequest(RadiusR.VPOS.Custom.VakifbankVPOSReference.VposRequest vposRequest) {
            return base.Channel.ExecuteVposRequest(vposRequest);
        }
        
        public System.Threading.Tasks.Task<RadiusR.VPOS.Custom.VakifbankVPOSReference.VposResponse> ExecuteVposRequestAsync(RadiusR.VPOS.Custom.VakifbankVPOSReference.VposRequest vposRequest) {
            return base.Channel.ExecuteVposRequestAsync(vposRequest);
        }
    }
}
