//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadiusR.Verimor.CallCenter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadiusR.Verimor.CallCenter.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Genel Arıza.
        /// </summary>
        public static string CompanyGeneralFault {
            get {
                return ResourceManager.GetString("CompanyGeneralFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi Kart Numarası.
        /// </summary>
        public static string CreditCardNo {
            get {
                return ResourceManager.GetString("CreditCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Tutar.
        /// </summary>
        public static string DebtAmount {
            get {
                return ResourceManager.GetString("DebtAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşleminizi şuan gerçekleştiremiyoruz. Sizi müşteri temsilcisine aktarıyorum. Lütfen bekleyiniz..
        /// </summary>
        public static string ExceptionPhrase {
            get {
                return ResourceManager.GetString("ExceptionPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TT Genel Arıza.
        /// </summary>
        public static string GeneralFault {
            get {
                return ResourceManager.GetString("GeneralFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Adı Soyadı.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödenmemiş fatura sayısı.
        /// </summary>
        public static string UnpaidBillCount {
            get {
                return ResourceManager.GetString("UnpaidBillCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınız: ([username])
        ///Şifreniz: ([password])
        ///Abone numaranız: ([subscriberNo])&apos;dir..
        /// </summary>
        public static string UserCredentialsText {
            get {
                return ResourceManager.GetString("UserCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış tuşlama yaptınız. {0}.
        /// </summary>
        public static string WrongDialingPhrase {
            get {
                return ResourceManager.GetString("WrongDialingPhrase", resourceCulture);
            }
        }
    }
}
